# Generated by Django 5.1.2 on 2025-11-01 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entries',
            name='phone',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='entries',
            name='pin',
            field=models.IntegerField(),
        ),
    ]
