# Generated by Django 5.1.2 on 2025-11-01 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0002_alter_entries_phone_alter_entries_pin'),
    ]

    operations = [
        migrations.AddField(
            model_name='entries',
            name='datetime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
