# Generated by Django 5.1.2 on 2025-11-12 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('job_title', models.CharField(choices=[('se', 'Software Engineer'), ('sde', 'Software Developer'), ('fullstack', 'Full stack developer'), ('pydev', 'Python developer'), ('reactdev', 'React developer'), ('mernstack', 'Mern stack'), ('qa', 'QA Roles')], max_length=10)),
                ('p_sumary', models.TextField(max_length=300)),
                ('skills', models.CharField(max_length=200)),
            ],
        ),
    ]
