# Generated by Django 5.1.2 on 2025-11-13 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='resume',
            field=models.FileField(blank=True, upload_to='resumes/'),
        ),
    ]
