# Generated by Django 5.1.2 on 2025-11-17 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweeter', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweet',
            old_name='create_at',
            new_name='created_at',
        ),
    ]
